---
language: go

sudo: required

install:
  # packages for packaging
  - go get -v github.com/asteris-llc/hammer
  - gem install fpm
  - sudo apt-get install rpm

  # packages for building Mesos
  - apt-get install build-essential python-dev python-boto libcurl4-nss-dev libsasl2-dev maven libapr1-dev libsvn-dev

script:
  - hammer build --output=/tmp/out

after_failure:
  - tail logs/*

deploy:
  provider: script
  script: /bin/bash scripts/bintray.sh /tmp/out
  on:
    branch: master
