---
language: go

env:
  - PACKAGE=marathon
  - PACKAGE=marathon-dynamic
  - PACKAGE=mesos-agent
  - PACKAGE=mesos-agent-dynamic
  - PACKAGE=mesos-master
  - PACKAGE=mesos-master-dynamic
  # we can't build Mesos on Travis right now because their version of GCC
  # (4.6.3) is less than the required version for building Mesos (4.6)
  # - PACKAGE=mesos

sudo: false

addons:
  apt:
    packages:
      # hammer
      - rpm

install:
  # packages for packaging
  - go get -v github.com/asteris-llc/hammer
  - gem install fpm

script:
  - hammer build --output=/tmp/out $PACKAGE

after_failure:
  - tail logs/*

deploy:
  provider: script
  script: /bin/bash scripts/bintray.sh /tmp/out
  on:
    branch: master
